name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: List Files After Checkout
        run: |
          pwd
          ls -la
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@ad41a6c27317e688719c813b0d6a25685a9bce54
        with:
          who-to-greet: John
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"